services:
  - type: web
    name: studyconnect
    env: python
    region: oregon
    plan: free
    buildCommand: bash render-build.sh
    startCommand: gunicorn studyconnect.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1
  - type: postgresql
    name: studyconnect
    ipWhitelist: []
