services:
  - type: web
    name: studyconnect
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn studyconnect.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        fromDatabase:
          name: studyconnect
          property: connectionString
  - type: postgresql
    name: studyconnect
    ipWhitelist: []
