services:
  - type: web
    name: studyconnect
    env: python
    region: oregon
    plan: free
    buildCommand: bash render-build.sh
    startCommand: cd studyconnect && gunicorn studyconnect.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1
  - type: postgresql
    name: studyconnect
    ipWhitelist: []
